import type { Locale } from "./locale";

export const HOME_COPY = {
  en: {
    heroH1: "Need a worker for a day? Or found one for the day?",
    heroLede:
      "Jugaadi connects shop owners and households with verified temporary workers nearby — for 1 day, 3 days, or a week.",
    ctaOwner: "I need workers",
    ctaWorker: "I want work",
    howHeading: "How it works",
    howOwnerH: "For shop & home owners",
    howOwnerSteps: ["Post what help you need and for how long", "See verified workers nearby", "Hire directly and pay them yourself"],
    howWorkerH: "For workers",
    howWorkerSteps: ["Register and add your skills", "See nearby jobs matching what you do", "Accept work and get hired"],
    findWorkersHeading: "Find workers near you",
    whoHeading: "Who it's for",
    whoItems: ["Kirana shop owners", "Small businesses", "Households needing maids, helpers, cleaners", "Part-time and daily wage workers looking for work"],
    pilotHeading: "Now piloting in one city",
    pilotText: "Join the waitlist to be first in when we launch near you.",
    waitlistPlaceholder: "Phone or email",
    seeHowHeading: "See how it works",
    seeHowText: "Read about direct hiring and worker verification.",
    browseFeatures: "Browse features",
    faqs: [
      { q: "What does Jugaadi actually do?", a: "Connects shop owners and households who need short-term help with nearby workers who can do that specific job, for 1 day to 1 week." },
      { q: "Is Jugaadi live in my city?", a: "We're running a single-city pilot right now. Join the waitlist below and we'll reach out as coverage expands." },
      { q: "Do workers need to pay anything?", a: "No. Sign up, add your skills, and apply to nearby jobs — Jugaadi doesn't charge workers in this pilot." },
    ],
  },
  hi: {
    heroH1: "एक दिन के लिए वर्कर चाहिए? या एक दिन के काम के लिए मिल गया?",
    heroLede: "Jugaadi दुकान मालिकों और घरों को पास के वेरिफाइड टेम्पररी वर्कर से जोड़ता है — 1 दिन, 3 दिन, या एक हफ्ते के लिए।",
    ctaOwner: "मुझे वर्कर चाहिए",
    ctaWorker: "मुझे काम चाहिए",
    howHeading: "यह कैसे काम करता है",
    howOwnerH: "दुकान और घर मालिकों के लिए",
    howOwnerSteps: ["बताएं आपको कौन सी मदद और कितने दिन के लिए चाहिए", "पास के वेरिफाइड वर्कर देखें", "सीधे हायर करें और खुद पेमेंट करें"],
    howWorkerH: "वर्कर्स के लिए",
    howWorkerSteps: ["रजिस्टर करें और अपनी स्किल्स जोड़ें", "अपने काम से मिलते-जुलते पास के जॉब देखें", "काम स्वीकार करें और हायर हो जाएं"],
    findWorkersHeading: "अपने पास वर्कर खोजें",
    whoHeading: "यह किसके लिए है",
    whoItems: ["किराना दुकान मालिक", "छोटे बिज़नेस", "घर जिन्हें मेड, हेल्पर, क्लीनर चाहिए", "पार्ट-टाइम और दिहाड़ी मज़दूर जो काम ढूंढ रहे हैं"],
    pilotHeading: "फ़िलहाल एक शहर में पायलट चल रहा है",
    pilotText: "वेटलिस्ट जॉइन करें, जब हम आपके पास लॉन्च करेंगे तो सबसे पहले बताएंगे।",
    waitlistPlaceholder: "फ़ोन या ईमेल",
    seeHowHeading: "देखें यह कैसे काम करता है",
    seeHowText: "डायरेक्ट हायरिंग और वर्कर वेरिफिकेशन के बारे में पढ़ें।",
    browseFeatures: "सुविधाएं देखें",
    faqs: [
      { q: "Jugaadi असल में क्या करता है?", a: "दुकान मालिकों और घरों को, जिन्हें थोड़े समय की मदद चाहिए, पास के ऐसे वर्कर से जोड़ता है जो वह खास काम 1 दिन से 1 हफ्ते तक कर सकें।" },
      { q: "क्या Jugaadi मेरे शहर में लाइव है?", a: "अभी हम सिर्फ एक शहर में पायलट चला रहे हैं। नीचे वेटलिस्ट जॉइन करें, कवरेज बढ़ने पर हम संपर्क करेंगे।" },
      { q: "क्या वर्कर्स को कुछ पेमेंट करना होता है?", a: "नहीं। साइन अप करें, अपनी स्किल्स जोड़ें, और पास के जॉब्स के लिए अप्लाई करें — इस पायलट में Jugaadi वर्कर्स से कोई चार्ज नहीं लेता।" },
    ],
  },
  hinglish: {
    heroH1: "Ek din ke liye worker chahiye? Ya ek din ke kaam ke liye mil gaya?",
    heroLede: "Jugaadi shop owners aur gharon ko paas ke verified temporary workers se jodta hai — 1 din, 3 din, ya ek hafte ke liye.",
    ctaOwner: "Mujhe worker chahiye",
    ctaWorker: "Mujhe kaam chahiye",
    howHeading: "Yeh kaise kaam karta hai",
    howOwnerH: "Shop aur home owners ke liye",
    howOwnerSteps: ["Batao aapko kaunsi help aur kitne din ke liye chahiye", "Paas ke verified workers dekho", "Directly hire karo aur khud payment karo"],
    howWorkerH: "Workers ke liye",
    howWorkerSteps: ["Register karo aur apni skills add karo", "Apne kaam se match karte nearby jobs dekho", "Kaam accept karo aur hire ho jao"],
    findWorkersHeading: "Apne paas worker dhoondo",
    whoHeading: "Yeh kiske liye hai",
    whoItems: ["Kirana shop owners", "Small businesses", "Ghar jinhe maid, helper, cleaner chahiye", "Part-time aur daily wage workers jo kaam dhoond rahe hain"],
    pilotHeading: "Abhi ek city mein pilot chal raha hai",
    pilotText: "Waitlist join karo, jab aapke area mein launch karenge toh sabse pehle bataenge.",
    waitlistPlaceholder: "Phone ya email",
    seeHowHeading: "Dekho yeh kaise kaam karta hai",
    seeHowText: "Direct hiring aur worker verification ke baare mein padho.",
    browseFeatures: "Features dekho",
    faqs: [
      { q: "Jugaadi actually karta kya hai?", a: "Shop owners aur gharon ko, jinhe short-term help chahiye, paas ke un workers se jodta hai jo woh specific kaam 1 din se 1 hafte tak kar sakein." },
      { q: "Kya Jugaadi meri city mein live hai?", a: "Abhi hum sirf ek city mein pilot chala rahe hain. Neeche waitlist join karo, coverage badhne par hum contact karenge." },
      { q: "Kya workers ko kuch pay karna padta hai?", a: "Nahi. Sign up karo, apni skills add karo, aur nearby jobs ke liye apply karo — is pilot mein Jugaadi workers se koi charge nahi leta." },
    ],
  },
} satisfies Record<Locale, unknown>;

export function homeCopy(locale: Locale) {
  return HOME_COPY[locale];
}
